name: Code quality check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black flake8 isort

    - name: Lint with Flake8
      run: python -m flake8 django_node_assets

    - name: Check with isort
      run: python -m isort django_node_assets --check

    - name: Check with Black
      run: python -m black django_node_assets --check
